name: GitHub Actions Demo
on: [push]
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install rpaframework
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0