name: GitHub Actions Demo
on: [push]

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install    
      - name: Generate build
        working-directory: ./Frontend
        run: npm start & npx wait-on http://localhost:3000
   
  robot_test:
    needs: react
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          browser: 'chrome'